### ISSUE TITLE
unable visualize face landmarks when run file main.py. can you share the file nvdsparse_retinaface.cpp has landmarks to build into a .so file

### ISSUE THREAD

**Issue by manhdoan291** [mrscarletzhou/retinaface-deepstream-python#1]

**Comment by manhdoan291** [comment]
thank you very much. but i run, i cannot see landmark on video 
![Screenshot from 2022-10-11 08-28-09](https://user-images.githubusercontent.com/45356143/194977055-f9a06980-cdbd-4630-a7c7-08ce7e1c6ca0.png)

**Comment by zhouyuchong** [comment]
@manhdoan291 deepstream doesn't support drawing landmarks using **custom parser** so far. if you want to visualize landmarks, you can get tensor-output of retinaface **trt** in a probe and draw lmks using **nvosd meta**. 

you can find examples [here](https://github.com/zhouyuchong/retinaface-deepstream-python/blob/b071b2c11834cf4ca9af46e73e9769b96bca7d6f/main.py#L162)

**Comment by manhdoan291** [comment]
please, how to get retinaface trt tensor-output correct to landmarks point ? 
I debug on code but value result_landmark = None
I am trying build lib .so have value result landmark. Is that true?

**Comment by manhdoan291** [comment]
@zhouyuchong i followed this link: https://forums.developer.nvidia.com/t/face-detection-with-deepstream-with-landmarks/120607
But I can't fix it. I cannot visualize landmark point on the deepstream because tensor-output is wrong.

**Comment by zhouyuchong** [comment]
> please, how to get retinaface trt tensor-output correct to landmarks point ? I debug on code but value result_landmark = None I am trying build lib .so have value result landmark. Is that true?

first of all, maybe you forget to set **output-tensor-meta=1** in retinaface config file. you can find its doc [here](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html#gst-nvinfer-file-configuration-specifications).

**Comment by zhouyuchong** [comment]
> @zhouyuchong i followed this link: https://forums.developer.nvidia.com/t/face-detection-with-deepstream-with-landmarks/120607 But I can't fix it. I cannot visualize landmark point on the deepstream because tensor-output is wrong.

I read this post and its [solution](https://forums.developer.nvidia.com/t/how-to-pass-the-5-landmarks-of-retinaface-and-perform-face-alignment-between-pgie-and-sgie/158140) is feasible. If you can save and pass landmarks in parser, you could modify **nvosd** codes to get lmks and draw it on screen.

**Comment by manhdoan291** [comment]
yes, you are right and after fixing it, i got the error again on line 178:
this link: https://github.com/zhouyuchong/retinaface-deepstream-python/blob/b071b2c11834cf4ca9af46e73e9769b96bca7d6f/main.py#L178
![Screenshot from 2022-10-12 09-35-37](https://user-images.githubusercontent.com/45356143/195236280-a2155862-3af7-4649-b1cb-ceee8e1badea.png)

How to fix it ?

**Comment by zhouyuchong** [comment]
> yes, you are right and after fixing it, i got the error again on line 178: this link:
> 
> https://github.com/zhouyuchong/retinaface-deepstream-python/blob/b071b2c11834cf4ca9af46e73e9769b96bca7d6f/main.py#L178
> 
> 
> ![Screenshot from 2022-10-12 09-35-37](https://user-images.githubusercontent.com/45356143/195236280-a2155862-3af7-4649-b1cb-ceee8e1badea.png)
> How to fix it ?

I think you already get the lmks data from your debug console. The only thing need to do now is draw them using **nvosd**. I'm sorry that I can't check codes for a while since I'm in quarantine. 
you can follow this [doc](https://docs.nvidia.com/metropolis/deepstream/python-api/PYTHON_API/NvOSD/NvOSD_CircleParams.html) to debug.

**Comment by zhouyuchong** [comment]
@manhdoan291 this repo can work now, have a try. :smile_cat:

**Comment by manhdoan291** [comment]
> @manhdoan291 this repo can work now, have a try. smile_cat
i tried but face-landmarks is wrong when visualize. it shows points in the wrong place on the face.

**Comment by manhdoan291** [comment]
@zhouyuchong 
it only shows correct face-landmarks with this repo
https://github.com/zhouyuchong/face-detect-deepstream

**Comment by zhouyuchong** [comment]
> > @manhdoan291 this repo can work now, have a try. smile_cat
> > i tried but face-landmarks is wrong when visualize. it shows points in the wrong place on the face.

that may be a ratio problem. Assuming your retinaface trt has a input of 640x480, you will get lmks' coordinates with same ratio. However, the video may have a different scale. you should check that.
