### ISSUE TITLE
tensorrtx离线运行retinaface和deepstream的结果不一致

### ISSUE THREAD

**Issue by Song-Gy** [mrscarletzhou/retinaface-deepstream-python#3]
我这边在retinaface转出的引擎进行了测试， 相同的场景下的输入图像， retinaface离线直接运行预测， 模型直接输出的结果大小是4, 经过nms， 结果为0； 但是在deepstream中， 模型输出的结果直接上涨到了1w+， nms的结果同样到达了1w+， 这个是什么原因导致的？ 我这边已经将你代码库里的nvinfer-custom库替换了原有的， 但是仍然又这个问题；

**Comment by zhouyuchong** [comment]
@Song-Gy 你是使用的tensorrtx吗？原repo的作者很久没有更新了，有些新的bug也没有修复。你可以使用我fork的那一个，或者自己更改retinaface对应的问题。参考[链接](https://forums.developer.nvidia.com/t/tensorrt-engine-giving-wrong-different-output-in-deepstream/139329/10)
+ [bug](https://github.com/wang-xinyu/tensorrtx/pull/485)
+ [fixed](https://github.com/zhouyuchong/tensorrtx)

**Comment by Song-Gy** [comment]
万分感谢， 这个卡了我好几天了
